# language
language: python
python:
  - "3.8"
# service
services:
   - docker
# install docker-compose
before_script: pip install docker-compose
# run command test in container django
script:
  - docker-compose run app sh -c "pytest ./tests/ && flake8"
